# Generated by Django 3.2.5 on 2021-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210913_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.DateField(verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
