# Generated by Django 3.2.5 on 2021-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dia_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.DateField(verbose_name=['%d-%m-%y ']),
        ),
    ]
