# Generated by Django 3.2.5 on 2021-09-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dia_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='hora',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.DateField(),
        ),
    ]
